os: linux

dist: focal

language: java

jdk:
    - openjdk16

cache:
    directories:
        - .autoconf
        - $HOME/.m2

install: true

script:
    - mvn clean install

after_success:
    - bash <(curl -s https://codecov.io/bash)
